#!/bin/sh

# update nginx configuration with env
envsubst '${MLRUN_API_PROXY_URL} \
          ${MLRUN_BETA_MODE} \
          ${MLRUN_FUNCTION_CATALOG_URL} \
          ${MLRUN_FUNCTION_CATALOG_PATH} \
          ${MLRUN_NUCLIO_API_URL} \
          ${MLRUN_NUCLIO_MODE} \
          ${MLRUN_NUCLIO_UI_URL} \
          ${MLRUN_V3IO_ACCESS_KEY} \
          ${MLRUN_IGZ_UI_ALLOWED_ORIGIN}' \
< /etc/nginx/conf.d/nginx.conf.tmpl \
> /etc/nginx/conf.d/nginx.conf

# update configuration with env
envsubst '${MLRUN_BETA_MODE} \
          ${MLRUN_NUCLIO_MODE} \
          ${MLRUN_NUCLIO_UI_URL}' \
< /usr/share/nginx/html/config.json.tmpl \
> /usr/share/nginx/html/config.json

# start nginx in the foreground
nginx -g 'daemon off;'
