export const JOBS_PAGE = 'JOBS'
export const FETCH_JOBS_BEGIN = 'FETCH_JOBS_BEGIN'
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_FAILURE = 'FETCH_JOBS_FAILURE'

export const FUNCTIONS_PAGE = 'FUNCTIONS'
export const FETCH_FUNCTIONS_BEGIN = 'FETCH_FUNCTIONS_BEGIN'
export const FETCH_FUNCTIONS_FAILURE = 'FETCH_FUNCTIONS_FAILURE'
export const FETCH_FUNCTIONS_SUCCESS = 'FETCH_FUNCTIONS_SUCCESS'

export const ARTIFACTS_PAGE = 'ARTIFACTS'
export const FETCH_ARTIFACTS_BEGIN = 'FETCH_ARTIFACTS_BEGIN'
export const FETCH_ARTIFACTS_SUCCESS = 'FETCH_ARTIFACTS_SUCCESS'
export const FETCH_ARTIFACTS_FAILURE = 'FETCH_ARTIFACTS_FAILURE'
export const ARTIFACT_PREVIEW = 'ARTIFACT_PREVIEW'
export const ARTIFACT_PREVIEW_CLOSE = 'ARTIFACT_PREVIEW_CLOSE'

export const FETCH_PROJECTS_BEGIN = 'FETCH_PROJECTS_BEGIN'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAILURE = 'FETCH_PROJECTS_FAILURE'

export const FETCH_JOB_LOGS_BEGIN = 'FETCH_JOB_LOGS_BEGIN'
export const FETCH_JOB_LOGS_SUCCESS = 'FETCH_JOB_LOGS_SUCCESS'
export const FETCH_JOB_LOGS_FAILURE = 'FETCH_JOB_LOGS_FAILURE'
export const REMOVE_JOB_LOGS = 'REMOVE_JOB_LOGS'

export const FETCH_ARTIFACT_PREVIEW_BEGIN = 'FETCH_ARTIFACT_PREVIEW_BEGIN'
export const FETCH_ARTIFACT_PREVIEW_SUCCESS = 'FETCH_ARTIFACT_PREVIEW_SUCCESS'
export const FETCH_ARTIFACT_PREVIEW_FAILURE = 'FETCH_ARTIFACT_PREVIEW_FAILURE'

export const SET_NEW_JOB_INPUTS = 'SET_NEW_JOB_INPUTS'
export const SET_NEW_JOB_VOLUMES = 'SET_NEW_JOB_VOLUMES'

export const SET_NEW_JOB_VOLUME_MOUNTS = 'SET_NEW_JOB_VOLUME_MOUNTS'
export const SET_NEW_JOB = 'SET_NEW_JOB'
export const SET_NEW_JOB_INPUT_PATH = 'SET_NEW_JOB_INPUT_PATH'
export const SET_NEW_JOB_OUTPUT_PATH = 'SET_NEW_JOB_OUTPUT_PATH'
